apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-test-app
  template:
    metadata:
      labels:
        app: hello-test-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hello-test-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: hello-test-app
        image: petkancho987/hello-test-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
