apiVersion: v1
kind: Service
metadata:
  name: hello-test-app-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http